server {
    listen 80;
    server_name _;

    charset utf-8;
    root /var/www/.next/;
    index index.html index.htm;
    location / {
            #         expires 3d;
            #         add_header Pragma "public";
            #         add_header Cache-Control "public";
        root /var/www;
        autoindex on;
        try_files $uri $uri/ /index.html =404;
    }

}